export interface Register {
    namesForm:string,
    surnameForm:string,
    lastnameForm:string,
    nationalityForm:string,
    bornForm: Date,
    CeduleForm:string,
    dateIssueForm:Date,
    expirationDateForm:Date,
    emailForm:string,
    phoneForm:string,
    temperatureForm:number,
    presionForm:string,
    saturationForm:string,
    bloodTypeForm:string,
}